var data = {
    "1995": [{
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "1996": [{
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "1997": [{
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "1998": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "1999": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2000": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2001": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2002": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2003": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2004": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2005": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2006": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2007": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "banned"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2008": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "banned"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "banned"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2009": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2010": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2011": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "banned"
    }, {
        "name": "MD",
        "class": "banned"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NY",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "banned"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2012": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "banned"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "banned"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "banned"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "banned"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "legal"
    }, {
        "name": "MD",
        "class": "legal"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "banned"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NY",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "legal"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2013": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "banned"
    }, {
        "name": "AZ",
        "class": "banned"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "legal"
    }, {
        "name": "CO",
        "class": "banned"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "legal"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "legal"
    }, {
        "name": "ID",
        "class": "banned"
    }, {
        "name": "IL",
        "class": "legal"
    }, {
        "name": "IN",
        "class": "banned"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "banned"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "legal"
    }, {
        "name": "MD",
        "class": "legal"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "legal"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "banned"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "banned"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NJ",
        "class": "legal"
    }, {
        "name": "NM",
        "class": "legal"
    }, {
        "name": "NY",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "banned"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "banned"
    }, {
        "name": "OR",
        "class": "banned"
    }, {
        "name": "PA",
        "class": "banned"
    }, {
        "name": "RI",
        "class": "legal"
    }, {
        "name": "SC",
        "class": "banned"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "banned"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "banned"
    }, {
        "name": "WA",
        "class": "legal"
    }, {
        "name": "WV",
        "class": "banned"
    }, {
        "name": "WI",
        "class": "banned"
    }, {
        "name": "WY",
        "class": "banned"
    }],
    "2014": [{
        "name": "AL",
        "class": "banned"
    }, {
        "name": "AK",
        "class": "legal"
    }, {
        "name": "AZ",
        "class": "legal"
    }, {
        "name": "AR",
        "class": "banned"
    }, {
        "name": "CA",
        "class": "legal"
    }, {
        "name": "CO",
        "class": "legal"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "legal"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "banned"
    }, {
        "name": "GA",
        "class": "banned"
    }, {
        "name": "HI",
        "class": "legal"
    }, {
        "name": "ID",
        "class": "legal"
    }, {
        "name": "IL",
        "class": "legal"
    }, {
        "name": "IN",
        "class": "legal"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "legal"
    }, {
        "name": "KY",
        "class": "banned"
    }, {
        "name": "LA",
        "class": "banned"
    }, {
        "name": "ME",
        "class": "legal"
    }, {
        "name": "MD",
        "class": "legal"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "banned"
    }, {
        "name": "MN",
        "class": "legal"
    }, {
        "name": "MS",
        "class": "banned"
    }, {
        "name": "MO",
        "class": "banned"
    }, {
        "name": "MT",
        "class": "legal"
    }, {
        "name": "NE",
        "class": "banned"
    }, {
        "name": "NV",
        "class": "legal"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NJ",
        "class": "legal"
    }, {
        "name": "NM",
        "class": "legal"
    }, {
        "name": "NY",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "legal"
    }, {
        "name": "ND",
        "class": "banned"
    }, {
        "name": "OH",
        "class": "banned"
    }, {
        "name": "OK",
        "class": "legal"
    }, {
        "name": "OR",
        "class": "legal"
    }, {
        "name": "PA",
        "class": "legal"
    }, {
        "name": "RI",
        "class": "legal"
    }, {
        "name": "SC",
        "class": "legal"
    }, {
        "name": "SD",
        "class": "banned"
    }, {
        "name": "TN",
        "class": "banned"
    }, {
        "name": "TX",
        "class": "banned"
    }, {
        "name": "UT",
        "class": "legal"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "legal"
    }, {
        "name": "WA",
        "class": "legal"
    }, {
        "name": "WV",
        "class": "legal"
    }, {
        "name": "WI",
        "class": "legal"
    }, {
        "name": "WY",
        "class": "legal"
    }],
    "2015": [{
        "name": "AL",
        "class": "legal"
    }, {
        "name": "AK",
        "class": "legal"
    }, {
        "name": "AZ",
        "class": "legal"
    }, {
        "name": "AR",
        "class": "legal"
    }, {
        "name": "CA",
        "class": "legal"
    }, {
        "name": "CO",
        "class": "legal"
    }, {
        "name": "CT",
        "class": "legal"
    }, {
        "name": "DE",
        "class": "legal"
    }, {
        "name": "DC",
        "class": "legal"
    }, {
        "name": "FL",
        "class": "legal"
    }, {
        "name": "GA",
        "class": "legal"
    }, {
        "name": "HI",
        "class": "legal"
    }, {
        "name": "ID",
        "class": "legal"
    }, {
        "name": "IL",
        "class": "legal"
    }, {
        "name": "IN",
        "class": "legal"
    }, {
        "name": "IA",
        "class": "legal"
    }, {
        "name": "KS",
        "class": "legal"
    }, {
        "name": "KY",
        "class": "legal"
    }, {
        "name": "LA",
        "class": "legal"
    }, {
        "name": "ME",
        "class": "legal"
    }, {
        "name": "MD",
        "class": "legal"
    }, {
        "name": "MA",
        "class": "legal"
    }, {
        "name": "MI",
        "class": "legal"
    }, {
        "name": "MN",
        "class": "legal"
    }, {
        "name": "MS",
        "class": "legal"
    }, {
        "name": "MO",
        "class": "legal"
    }, {
        "name": "MT",
        "class": "legal"
    }, {
        "name": "NE",
        "class": "legal"
    }, {
        "name": "NV",
        "class": "legal"
    }, {
        "name": "NH",
        "class": "legal"
    }, {
        "name": "NJ",
        "class": "legal"
    }, {
        "name": "NM",
        "class": "legal"
    }, {
        "name": "NY",
        "class": "legal"
    }, {
        "name": "NC",
        "class": "legal"
    }, {
        "name": "ND",
        "class": "legal"
    }, {
        "name": "OH",
        "class": "legal"
    }, {
        "name": "OK",
        "class": "legal"
    }, {
        "name": "OR",
        "class": "legal"
    }, {
        "name": "PA",
        "class": "legal"
    }, {
        "name": "RI",
        "class": "legal"
    }, {
        "name": "SC",
        "class": "legal"
    }, {
        "name": "SD",
        "class": "legal"
    }, {
        "name": "TN",
        "class": "legal"
    }, {
        "name": "TX",
        "class": "legal"
    }, {
        "name": "UT",
        "class": "legal"
    }, {
        "name": "VT",
        "class": "legal"
    }, {
        "name": "VA",
        "class": "legal"
    }, {
        "name": "WA",
        "class": "legal"
    }, {
        "name": "WV",
        "class": "legal"
    }, {
        "name": "WI",
        "class": "legal"
    }, {
        "name": "WY",
        "class": "legal"
    }]
};
